[build]
  publish = "."
  command = ""   # situs statis, tidak butuh build

# Redirect opsional (bisa juga atur Primary domain di Netlify UI)
[[redirects]]
  from = "https://www.original4d.store/*"
  to = "https://original4d.store/:splat"
  status = 301
  force = true

# Headers global
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), browsing-topics=()"
    # Sesuaikan CSP dgn inline script & JSON-LD:
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline';
      style-src 'self' 'unsafe-inline';
      img-src 'self' data:;
      font-src 'self' data:;
      object-src 'none';
      base-uri 'self';
      frame-ancestors 'self';
      connect-src 'self';
    """

# Cache policy
[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/amp.index.html"
  [headers.values]
    Cache-Control = "no-cache"
